config/routes.rb
Rails.application.routes.draw do
  resources :recommendations do
    get :likes
    collection do
      get :search
    end
  end

  root "recommendations#index"
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  validates :title, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def new
    @recommendation = Recommendation.new
  end

  def index
    @recommendations = Recommendation.all
  end

  def create
    @recommendation = Recommendation.create(params.require(:recommendation).permit([:title, :description, :url, :tag, :likes]))
    if @recommendation.errors.messages.blank?
      render :show
    else
      render :new
    end
  end

  def likes
    @recommendation = Recommendation.find(params[:recommendation_id])
    @recommendation.likes += 1
    @recommendation.save
    redirect_to(root_url)
  end

  def search
    @search_results = Recommendation.where(tag: params[:query])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shelf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recommendations/index.html.erb
<br><br><br><br>
<form class="form-search" align = "middle" action="/recommendations/search">
  <input type="text" class="input-medium search-query" name="query">
  <button type="submit" class="btn">Search</button>
  <%= link_to "New Recommendation", new_recommendation_path, class: "btn btn-primary btn-large" %>
</form>

<h1 >Recommendations For You</h1>
<div class="recommendations-list" >
  <% @recommendations.each do |recommendation|  %>
    <ul class="recommendation" >
      <li ><h3><%= "#{recommendation.title} : #{recommendation.description} : #{recommendation.url} : #{recommendation.tag}"%>
        <%= link_to "+#{recommendation.likes}", recommendation_likes_path(recommendation) %>
      </h3></li>
    </ul>
  <% end %>
</div>

app/views/recommendations/new.html.erb
<%= form_for @recommendation  do |f|%>
<fieldset>
    <legend>Your new recommendation</legend>
    <table><tr>
        <% if !@recommendation.errors.messages[:title].blank? and !@recommendation.errors.messages[:url].blank? %>
        <td><div>Title and Url cannot be empty</div></td>
        <% elsif !@recommendation.errors.messages[:title].blank?%>
        <td><div>Title cannot be empty</div></td>
        <% elsif !@recommendation.errors.messages[:url].blank? %>
        <td><div>Url cannot be empty</div></td>
        <% end %></tr>
    </table>
    <div />

    <div>
        <table>
           <tr>
               <td>
                <%= f.label :title %>
                <%= f.text_field :title %>
            </td><td>
            <%= f.label :description %>
            <%= f.text_field :description %></td><td>
            <%= f.label :url %>
            <%= f.text_field :url %></td><td>
            <%= f.label :tag %>
            <%= f.text_field :tag %></td><td>
            <%= f.submit "Create", class: "btn btn-success" %></td></tr>
        </table>
    </div>

</fieldset>
<% end %>

app/views/recommendations/search.html.erb
<div class="page-header">
  <h1>  Search Results </h1>
</div>
<div class="recommendations-list">
 <% @search_results.each do |recommendation|  %>
  <ul class="recommendation">
    <li>
      <h3>
      <%= "#{recommendation.title} : #{recommendation.description} : #{recommendation.url} : #{ recommendation.tag}"%>
      </h3>
    </li>
  </ul>
  <% end %>
</div>

app/views/recommendations/show.html.erb
Voila! you just created a new recommendation with a tag
<%= "#{@recommendation.title} : #{@recommendation.description} : #{@recommendation.url} : #{@recommendation.tag}" %>